# -*- coding: utf-8 -*-
"""cnn_MNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DGLFTMBGqmS1khq9O_NGO9ZcROWEE0t3
"""

from tensorflow import keras
from keras import models, layers, datasets
import matplotlib.pyplot as plt
import numpy as np

(X_train,y_train),(X_test,y_test)=keras.datasets.mnist.load_data()

X_train=X_train/255.
X_test=X_test/255.

model=models.Sequential([
    layers.Conv2D(30,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(100,activation='relu'),
    layers.Dense(10, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5)

model.evaluate(X_test,y_test)