# -*- coding: utf-8 -*-
"""obj_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrckYE7tyjwR240M3kS1Jfr7LtJpbPen
"""

# Install required libraries
!pip install tensorflow-gpu==2.7.0
!pip install keras==2.4.3
!pip install opencv-python-headless==4.5.4.58
!pip install numpy==1.19.5
!pip install pillow==8.3.2
!pip install matplotlib==3.2.2

# Download the RetinaNet model
!wget https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5
!wget -O 'input.jpg' https://images.unsplash.com/photo-1594028411108-96a5b0302a4a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80

!pip install imageai==2.1.6

# Import necessary libraries
import os
from imageai.Detection import ObjectDetection
import matplotlib.pyplot as plt
from PIL import Image


# Create object detection instance
detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath("resnet50_coco_best_v2.1.0.h5")
detector.loadModel()

# Detect objects in input image
detections = detector.detectObjectsFromImage(input_image='/content/input.jpg', output_image_path='output.jpg')

# Print detected objects and their probabilities
for detection in detections:
    print(detection["name"], " : ", detection["percentage_probability"])